source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'SQMessages' do
    #use_frameworks!
    pod "SQMessages", :path => "../"
end

target 'Tests' do
    #use_frameworks!
  pod "SQMessages", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
